name: stream_dart
version: 1.0.0
description: Stream SDK for Dart
homepage: https://getstream.io/


environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  dio: '^5.7.0'
  equatable: '^2.0.7'
  json_annotation: '^4.9.0'

  jose_plus: any
dev_dependencies:
  build_runner: any
  json_serializable: '^6.9.3'
  test: '^1.16.0'
  very_good_analysis: ^10.0.0
